# Generated by Django 6.1.1 on 2026-10-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('temperature', models.FloatField(help_text='°C')),
                ('humidity', models.FloatField(help_text='% relative humidity')),
                ('water_level', models.FloatField(help_text='% of tank capacity')),
                ('shade_net_active', models.BooleanField(help_text='True when the shade net motor is running/deployed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
