# Generated by Django 6.1.1 on 2026-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reading',
            name='source',
            field=models.CharField(default='direct', help_text='direct (WiFi/HTTP) or lorawan', max_length=20),
        ),
    ]
