# Generated by Django 6.1.1 on 2026-10-03 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_reading_device_id_reading_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
